services:
  postgres:
    image: 'postgres:16'
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgres

  api:
    build: .
    ports:
      - ${SERVER_PORT}:8080
    env_file:
      - .env
    depends_on:
      - postgres