spring:
  profiles:
    active: ${APP_PROFILE:dev}
  server:
    port: ${SERVER_PORT:8080}
  doc:
    swagger-ui:
      path: /docs.html
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  jackson:
    property-naming-strategy: SNAKE_CASE
