# TEST
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_db
    username: travel
    password: password
api:
  security:
    token:
      secret: secret
      issuer: issuer
      duration_in_hours: 1
app:
  rate:
    limit: 1
    durationinms: 6000
geodb:
  url: http://geodb-free-service.wirefreethought.com/v1
openweather:
  url: https://api.openweathermap.org/data/2.5
  key: add_your_key_here
exchangerates:
  url: http://api.exchangeratesapi.io
  api:
    key: api_key_here
wordlbank:
  url: https://api.worldbank.org
restcountries:
  url: https://restcountries.com/v3.1
