# TEST
# For some reason, integration tests are not detecting .env variables
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_db
    username: travel
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
api:
  security:
    token:
      secret: secret
      issuer: issuer
      duration_in_hours: 1
app:
  rate:
    limit: 300
    durationinms: 6000
geodb:
  url: http://geodb-free-service.wirefreethought.com/v1
openweather:
  url: https://api.openweathermap.org/data/2.5
  key: 52cd50263b9bd19f535b365d6bc2ce49
exchangerates:
  url: http://api.exchangeratesapi.io
  api:
    key: api_key_here
wordlbank:
  url: https://api.worldbank.org
restcountries:
  url: https://restcountries.com/v3.1
